import React from 'react';
import { ZonosCustomsItem, MaterialSourceType } from '../../types/zonosCustoms';
import { generateZonosCustomsDescription, suggestMaterialAndProductType } from '../../utils/zonosCustomsValidation';

interface ZonosItemEditorProps {
  item: ZonosCustomsItem;
  itemNumber: number;
  isLocked: boolean;
  onUpdate: (updated: ZonosCustomsItem) => void;
  onDelete: (id: string) => void;
}

export const ZonosItemEditor: React.FC<ZonosItemEditorProps> = ({
  item,
  itemNumber,
  isLocked,
  onUpdate,
  onDelete
}) => {
  const handleMaterialChange = (material: string) => {
    if (isLocked) return;
    let cleanMat = material;
    if (cleanMat.toLowerCase() === 'plastic' || cleanMat.toLowerCase() === 'plastics') {
      cleanMat = 'PVC';
    }
    const autoDesc = generateZonosCustomsDescription(item.title || '', cleanMat, item.productType);
    onUpdate({
      ...item,
      material: cleanMat,
      customsDescription: autoDesc,
      materialSource: 'manual',
      isEditedByUser: true
    });
  };

  const handleProductTypeChange = (productType: string) => {
    if (isLocked) return;
    const autoDesc = generateZonosCustomsDescription(item.title || '', item.material, productType);
    onUpdate({
      ...item,
      productType,
      customsDescription: autoDesc,
      isEditedByUser: true
    });
  };

  const handleCustomsDescriptionChange = (customsDescription: string) => {
    if (isLocked) return;
    onUpdate({
      ...item,
      customsDescription,
      isEditedByUser: true
    });
  };

  const handleQuantityChange = (qtyVal: number) => {
    if (isLocked) return;
    const quantity = Math.max(1, qtyVal || 1);
    const unitJpy = item.unitValueJpy || 0;
    onUpdate({
      ...item,
      quantity,
      totalValueJpy: Math.round(unitJpy * quantity)
    });
  };

  const handleUnitJpyChange = (valStr: string) => {
    if (isLocked) return;
    const unitJpy = Math.max(0, parseInt(valStr) || 0);
    const totalJpy = Math.round(unitJpy * Math.max(1, item.quantity));
    onUpdate({
      ...item,
      unitValueJpy: unitJpy,
      totalValueJpy: totalJpy,
      isEditedByUser: true
    });
  };

  const handleOriginChange = (origin: string) => {
    if (isLocked) return;
    const cleanOrigin = origin.trim();
    const warning = cleanOrigin.toLowerCase() !== 'japan' && cleanOrigin.toLowerCase() !== 'jp';
    onUpdate({
      ...item,
      countryOfOrigin: cleanOrigin || 'Japan',
      originWarning: warning
    });
  };

  const handleToggleFreeGift = (isGift: boolean) => {
    if (isLocked) return;
    onUpdate({
      ...item,
      isFreeGift: isGift,
      isIncludedItem: isGift,
      isSoldItem: !isGift
    });
  };

  const handleAutoGenerateDescription = () => {
    if (isLocked) return;
    const desc = generateZonosCustomsDescription(item.title || '', item.material, item.productType);
    onUpdate({
      ...item,
      customsDescription: desc
    });
  };

  const renderMaterialSourceBadge = (source?: MaterialSourceType) => {
    switch (source) {
      case 'ebay':
        return <span className="bg-blue-900/80 text-blue-300 border border-blue-600/50 text-[10px] px-1.5 py-0.5 rounded font-semibold">eBay情報</span>;
      case 'inferred_listing':
        return <span className="bg-emerald-900/80 text-emerald-300 border border-emerald-600/50 text-[10px] px-1.5 py-0.5 rounded font-semibold">素材推定</span>;
      case 'inferred_photo':
        return <span className="bg-amber-900/80 text-amber-300 border border-amber-600/50 text-[10px] px-1.5 py-0.5 rounded font-semibold">画像推定</span>;
      case 'manual':
        return <span className="bg-purple-900/80 text-purple-300 border border-purple-600/50 text-[10px] px-1.5 py-0.5 rounded font-semibold">手入力</span>;
      default:
        return <span className="bg-slate-800 text-slate-400 border border-slate-700 text-[10px] px-1.5 py-0.5 rounded font-semibold">未設定</span>;
    }
  };

  return (
    <div className={`zonos-item-editor card border-slate-700 bg-slate-900 p-3 rounded-lg space-y-3 ${isLocked ? 'opacity-85' : ''}`}>
      <div className="card-header flex justify-between items-center pb-2 border-b border-slate-800">
        <div className="flex items-center space-x-2">
          <span className="bg-slate-800 text-slate-200 font-mono text-xs px-2 py-0.5 rounded border border-slate-700 font-bold">
            品目 #{itemNumber}
          </span>

          {item.isFreeGift || item.isIncludedItem ? (
            <span className="bg-amber-950 text-amber-400 border border-amber-600/60 text-xs px-2 py-0.5 rounded font-bold flex items-center gap-1">
              🎁 おまけ・同梱品 (Free Gift)
            </span>
          ) : (
            <span className="bg-emerald-950 text-emerald-400 border border-emerald-600/60 text-xs px-2 py-0.5 rounded font-bold flex items-center gap-1">
              📦 販売商品 (Regular Item)
            </span>
          )}

          {renderMaterialSourceBadge(item.materialSource)}

          {item.originWarning && (
            <span className="bg-red-950 text-red-300 border border-red-500/80 text-xs px-2 py-0.5 rounded font-bold animate-pulse">
              ⚠️ 原産国要確認
            </span>
          )}
        </div>

        {!isLocked && (item.isFreeGift || item.isIncludedItem) && (
          <button
            type="button"
            className="text-red-400 hover:text-red-300 font-bold text-sm"
            onClick={() => onDelete(item.id)}
            title="このおまけ項目を削除"
          >
            ✕ 削除
          </button>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 text-xs">
        {/* eBay Title & Banner */}
        {item.title && (
          <div className="col-span-full bg-slate-950 p-2.5 rounded border border-slate-800 flex items-center space-x-3">
            {item.imageUrl && (
              <img
                src={item.imageUrl}
                alt={item.title}
                className="w-12 h-12 object-cover rounded border border-slate-700"
                onError={(e) => {
                  (e.target as HTMLImageElement).src = 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=150&auto=format&fit=crop&q=80';
                }}
              />
            )}
            <div className="overflow-hidden">
              <div className="text-[11px] text-slate-400 flex items-center gap-2">
                <span>eBay Item ID: {item.itemId || 'N/A'}</span>
              </div>
              <p className="font-semibold text-slate-200 truncate">{item.title}</p>
            </div>
          </div>
        )}

        {/* 1. Customs Description (English) */}
        <div className="col-span-2 space-y-1">
          <div className="flex justify-between items-center">
            <label className="font-bold text-slate-300">Customs Description (英語品名)</label>
            {!isLocked && (
              <button
                type="button"
                className="text-[10px] text-blue-400 hover:text-blue-300 underline font-semibold"
                onClick={handleAutoGenerateDescription}
              >
                ✨ 英文品名を自動生成
              </button>
            )}
          </div>
          <input
            type="text"
            className="form-control text-xs font-mono bg-slate-950 border-slate-700 text-emerald-300 font-bold"
            placeholder="例: PVC figure, Paper sticky note, Acrylic keychain"
            value={item.customsDescription || generateZonosCustomsDescription(item.title || '', item.material, item.productType)}
            onChange={(e) => handleCustomsDescriptionChange(e.target.value)}
            disabled={isLocked}
          />
          <span className="text-[10px] text-slate-400">
            ※文字数: {(item.customsDescription || '').length} 文字 (推奨 約30文字 / 材質 + 商品種別)
          </span>
        </div>

        {/* 2. 材質 (Material) */}
        <div className="space-y-1">
          <label className="font-bold text-slate-300 block">材質 (Material)</label>
          <input
            type="text"
            className="form-control text-xs bg-slate-950 border-slate-700 text-slate-200"
            placeholder="例: PVC, Paper, Acrylic, Cotton"
            value={item.material}
            onChange={(e) => handleMaterialChange(e.target.value)}
            disabled={isLocked}
          />
        </div>

        {/* 3. 商品種類 (Product Type) */}
        <div className="space-y-1">
          <label className="font-bold text-slate-300 block">商品種類 (Product Type)</label>
          <input
            type="text"
            className="form-control text-xs bg-slate-950 border-slate-700 text-slate-200"
            placeholder="例: Figure, Sticky Note, Keychain"
            value={item.productType}
            onChange={(e) => handleProductTypeChange(e.target.value)}
            disabled={isLocked}
          />
        </div>

        {/* 4. 区分 toggle */}
        <div className="space-y-1">
          <label className="font-bold text-slate-300 block">区分 (Type)</label>
          <select
            className="form-control text-xs bg-slate-950 border-slate-700 text-slate-200"
            value={item.isFreeGift || item.isIncludedItem ? 'gift' : 'regular'}
            onChange={(e) => handleToggleFreeGift(e.target.value === 'gift')}
            disabled={isLocked}
          >
            <option value="regular">販売商品 (Regular Item)</option>
            <option value="gift">おまけ・同梱品 (Free Gift)</option>
          </select>
        </div>

        {/* 5. 数量 (Quantity) */}
        <div className="space-y-1">
          <label className="font-bold text-slate-300 block">数量 (Qty)</label>
          <input
            type="number"
            className="form-control text-xs bg-slate-950 border-slate-700 text-slate-200 font-mono"
            min="1"
            value={item.quantity}
            onChange={(e) => handleQuantityChange(parseInt(e.target.value) || 1)}
            disabled={isLocked}
          />
        </div>

        {/* 6. 単価 (Unit Value JPY) */}
        <div className="space-y-1">
          <label className="font-bold text-slate-300 block">申告単価 (JPY)</label>
          <div className="flex items-center space-x-1">
            <input
              type="number"
              className="form-control text-xs bg-slate-950 border-slate-700 text-amber-300 font-mono font-bold"
              min="1"
              value={item.unitValueJpy || 0}
              onChange={(e) => handleUnitJpyChange(e.target.value)}
              disabled={isLocked}
            />
            <span className="text-slate-400 text-xs">円</span>
          </div>
        </div>

        {/* 7. 小計 (Subtotal JPY) */}
        <div className="space-y-1">
          <label className="font-bold text-slate-300 block">申告小計 (JPY)</label>
          <div className="p-2 bg-slate-950 border border-slate-800 rounded font-mono font-bold text-emerald-400 text-xs flex justify-between items-center">
            <span>{((item.unitValueJpy || 0) * Math.max(1, item.quantity)).toLocaleString()} 円</span>
          </div>
        </div>

        {/* 8. 原産国 (Country of Origin) */}
        <div className="space-y-1 col-span-1">
          <label className="font-bold text-slate-300 block">原産国 (Country of Origin)</label>
          <input
            type="text"
            className="form-control text-xs bg-slate-950 border-slate-700 text-slate-200"
            placeholder="Japan"
            value={item.countryOfOrigin || 'Japan'}
            onChange={(e) => handleOriginChange(e.target.value)}
            disabled={isLocked}
          />
        </div>
      </div>
    </div>
  );
};
