import { buildShopeeSgTokenExchangePreview } from '../shopeeSgTokenExchangePreviewClient';
import { describeBackendError } from '../ebaySandboxBackendClient';

function jsonResponse(payload: unknown, status = 200): Response { return new Response(JSON.stringify(payload), { status, headers: { 'Content-Type': 'application/json' } }); }

export async function runShopeeSgTokenExchangePreviewClientTests(): Promise<{ passed: number; failed: number; log: string[] }> {
  let passed = 0; let failed = 0; const log: string[] = [];
  const assert = (condition: boolean, name: string) => { if (condition) { passed++; log.push(`✅ [PASS] ${name}`); } else { failed++; log.push(`❌ [FAIL] ${name}`); } };
  const auth: any = { verificationId: 'auth-token-client', status: 'OFFICIAL_AUTH_SCHEMA_VERIFIED', officialSourceUrl: 'https://open.shopee.com/auth', tokenEndpoint: 'https://partner.shopeemobile.com/api/v2/auth/token/get', signatureAlgorithm: 'HMAC-SHA256', checkedAt: '2026-09-09T03:00:00Z', currentSingaporeApplicabilityConfirmed: true, externalNetworkAllowed: false, externalWriteAllowed: false, secretsStored: false };
  const mapping: any = { tokenMappingId: 'token-map-client', marketplaceRegion: 'SG', status: 'STRUCTURED_TOKEN_MAPPING_VERIFIED', authSchemaVerificationId: auth.verificationId, officialSourceUrl: auth.officialSourceUrl, tokenEndpoint: auth.tokenEndpoint, tokenHttpMethod: 'POST', tokenBodyEncoding: 'JSON', tokenQueryFieldNames: { partnerId: 'partner_id', timestamp: 'timestamp', signature: 'sign' }, tokenQueryOrder: ['PARTNER_ID_QUERY','TIMESTAMP_QUERY','SIGNATURE_QUERY'], tokenBodyFieldNames: { authorizationCode: 'code', shopId: 'shop_id', partnerId: 'partner_id' }, tokenBodyRoles: ['AUTHORIZATION_CODE_BODY','SHOP_ID_BODY','PARTNER_ID_BODY'], signatureAlgorithm: 'HMAC-SHA256', signatureBaseComponents: ['PARTNER_ID','API_PATH','TIMESTAMP'], tokenResponseFieldNames: { accessToken: 'access_token', refreshToken: 'refresh_token', expiresIn: 'expire_in' }, expiresInUnit: 'SECONDS', allRequiredRequestFieldsRepresented: true, allRequiredResponseFieldsRepresented: true, checkedAt: '2026-09-09T03:10:00Z', currentSingaporeApplicabilityConfirmed: true, tokenExchangeAllowed: false, externalNetworkAllowed: false, externalWriteAllowed: false, secretsStored: false };
  const runtime: any = { runtimeVerificationId: 'token-runtime-client', marketplaceRegion: 'SG', status: 'TOKEN_EXCHANGE_RUNTIME_VERIFIED', authSchemaVerificationId: auth.verificationId, tokenMappingId: mapping.tokenMappingId, officialSourceUrl: auth.officialSourceUrl, signatureAlgorithmLabel: 'HMAC-SHA256', signatureImplementation: 'HMAC_SHA256_HEX', signatureBaseSerialization: 'CONCAT_NO_SEPARATOR', checkedAt: '2026-09-09T03:20:00Z', currentSingaporeApplicabilityConfirmed: true, previewAllowed: true, tokenExchangeAllowed: false, externalNetworkAllowed: false, externalWriteAllowed: false, secretValuesStored: false };

  let url = ''; let init: RequestInit | undefined;
  const result = await buildShopeeSgTokenExchangePreview({ accountId: ' shopee_sg_main ', shopId: ' 99887766 ', credentialRef: ' SHOPEE_SG_MAIN ', authSchemaVerification: auth, tokenMapping: mapping, tokenRuntimeVerification: runtime }, 'http://localhost:3001/', async (input, requestInit) => {
    url = String(input); init = requestInit;
    return jsonResponse({ success: true, marketplace: 'Shopee', marketplaceRegion: 'SG', mode: 'TOKEN_EXCHANGE_REQUEST_PREVIEW_NO_NETWORK', accountId: 'shopee_sg_main', shopId: '99887766', credentialRef: 'SHOPEE_SG_MAIN', authSchemaVerificationId: auth.verificationId, tokenMappingId: mapping.tokenMappingId, runtimeVerificationId: runtime.runtimeVerificationId, tokenEndpoint: auth.tokenEndpoint, requestMethod: 'POST', bodyEncoding: 'JSON', queryFields: [{ role: 'PARTNER_ID_QUERY', fieldName: 'partner_id' }], bodyFields: [{ role: 'AUTHORIZATION_CODE_BODY', fieldName: 'code' }], responseFields: { accessToken: 'access_token', refreshToken: 'refresh_token', expiresIn: 'expire_in', expiresInUnit: 'SECONDS' }, signatureComponentRoles: ['PARTNER_ID','API_PATH','TIMESTAMP'], signatureImplementation: 'HMAC_SHA256_HEX', signatureBaseSerialization: 'CONCAT_NO_SEPARATOR', signatureGenerated: true, signatureLength: 64, authorizationCodeSource: 'SYNTHETIC_PREVIEW_ONLY', authorizationCodeStored: false, authorizationCodeReturned: false, partnerIdValueReturned: false, partnerKeyValueReturned: false, signatureValueReturned: false, signatureBaseReturned: false, tokenValuesReturned: false, executableRequestReturned: false, secretValuesReturned: false, requestFingerprint: 'a'.repeat(64), timestampPreview: 1, canExchangeToken: false, canStoreTokens: false, sendAllowed: false, networkAction: 'NONE', externalWritePerformed: false, blockingReasons: ['Preview only.'] });
  });
  assert(url === 'http://localhost:3001/api/shopee/sg/auth/token-exchange/preview' && init?.method === 'POST', 'Test 1: Token preview uses dedicated backend endpoint');
  const sent = JSON.parse(String(init?.body || '{}')); const sentText = JSON.stringify(sent).toLowerCase();
  assert(sent.accountId === 'shopee_sg_main' && sent.shopId === '99887766' && sent.credentialRef === 'SHOPEE_SG_MAIN', 'Test 2: Client normalizes safe Shopee identity');
  assert(sent.tokenMapping.tokenMappingId === mapping.tokenMappingId && sent.tokenRuntimeVerification.runtimeVerificationId === runtime.runtimeVerificationId, 'Test 3: Exact token mapping/runtime evidence IDs are sent');
  assert(!sentText.includes('partner_key') && !sentText.includes('authorization_code=') && !sentText.includes('access_token=') && !sentText.includes('refresh_token='), 'Test 4: Client sends no secret values or real authorization code');
  assert(result.authorizationCodeSource === 'SYNTHETIC_PREVIEW_ONLY' && result.authorizationCodeReturned === false && result.tokenValuesReturned === false, 'Test 5: Response confirms synthetic-code preview with no token values');
  assert(result.canExchangeToken === false && result.sendAllowed === false && result.networkAction === 'NONE', 'Test 6: Preview remains non-network and non-executable');
  let called = false;
  try { await buildShopeeSgTokenExchangePreview({ accountId: 'x', shopId: 'bad', credentialRef: 'SHOPEE_SG_MAIN', authSchemaVerification: auth, tokenMapping: mapping, tokenRuntimeVerification: runtime }, 'http://localhost:3001', async () => { called = true; return jsonResponse({}); }); assert(false, 'Test 7: Invalid Shop ID should fail'); }
  catch (error) { assert(!called && describeBackendError(error).includes('INVALID_SHOPEE_SHOP_ID'), 'Test 7: Invalid Shop ID is blocked before backend call'); }
  try { await buildShopeeSgTokenExchangePreview({ accountId: 'x', shopId: '1', credentialRef: 'SHOPEE_SG_MAIN', authSchemaVerification: auth, tokenMapping: mapping, tokenRuntimeVerification: runtime }, 'http://localhost:3001', async () => jsonResponse({ success: false, errorCode: 'STALE_SHOPEE_TOKEN_MAPPING', error: 'stale', networkAction: 'NONE', externalWritePerformed: false }, 409)); assert(false, 'Test 8: Backend stale mapping should fail'); }
  catch (error) { assert(describeBackendError(error).includes('STALE_SHOPEE_TOKEN_MAPPING'), 'Test 8: Backend safe error code is preserved'); }
  return { passed, failed, log };
}
